# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RxSwiftLearn' do
    pod 'RxSwift',    '~> 2.0'
    pod 'RxCocoa',    '~> 2.0'
    pod 'Alamofire', '~> 3.4.0'
    pod 'ObjectMapper', '~> 1.3.0'
end

